BugFix - Which is newline terminated causing execution to fail
sensu-plugins/sensu-plugins-varnish pull request #13
Opened 2017-08-02 17:12 UTC by warmfusion

Bugfix - Found that which returns newline's on strings which doesn't actually work as expected.

Don't know how this snuck through my testing on the host - we ensure that the newline is removed with a simple strip.

`Which` should never return multiple responses.
#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] Update README with any necessary configuration snippets

~- [ ] Binstubs are created if needed~

- [ ] RuboCop passes

- [ ] Existing tests pass

2017-08-05 21:06 UTC, majormoses requested changes
Good catch, I'd prefer we use `chmop` over `strip` because strip starts at the beginging of the string where chmop starts at the end in a minor net performance. You can read of the difference here: https://www.quora.com/What-is-the-difference-between-chomp-and-strip-in-Ruby

2017-08-05 21:06 UTC, majormoses commented on bin/check-varnish-status.rb
> +    varnishadm = `which varnishadm 2>/dev/null`.strip
`chmop` would be a better choice

2017-08-05 21:06 UTC, majormoses commented on bin/metrics-varnish.rb
> +    varnishstat_command = `which varnishstat 2>/dev/null`.strip
`chmop` would be a better choice

2017-08-18 13:27 UTC, rponcetn commented
Hi guys, Why is it not yet merged? , I have the same error. Can not make the change by chomp or strip?

2017-08-18 15:53 UTC, majormoses commented
@rponcetn I reviewed this and I suggested an alternative which is more performant and I have not heard back. Given the lack of response I am gonna merge (to give credit) and change it myself to.

2017-08-18 15:54 UTC, majormoses approved these changes

2017-08-18 15:56 UTC, merged

2017-08-18 16:05 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-varnish/versions/1.1.1